# cloudbuild-frontend-production.yaml
steps:
  # Paso 1: Instalar dependencias
  - name: 'node:20'
    entrypoint: npm
    args: ['install']
    dir: 'frontend'

  # Paso 2: Ejecutar Linter para verificar la calidad del código
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'lint']
    dir: 'frontend'

  # Paso 3: Construir la aplicación de producción
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    dir: 'frontend'

  # Paso 4: Desplegar a Firebase Hosting
  - name: 'node:20'
    entrypoint: npx
    args:
      - 'firebase'
      - 'deploy'
      - '--project'
      - '${PROJECT_ID}' # Usa el ID del proyecto de la compilación
      - '--only'
      - 'hosting'
      - '-m'
      - 'Deploy from Cloud Build: ${SHORT_SHA}' # Mensaje del despliegue
    dir: 'frontend'

# Opciones de la compilación
options:
  logging: CLOUD_LOGGING_ONLY
