"""Initial migration

Revision ID: bbdb4c480ed9
Revises:
Create Date: 2025-10-31 20:53:09.694710

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bbdb4c480ed9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categorias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_index(op.f("ix_categorias_id"), "categorias", ["id"], unique=False)
    op.create_table(
        "plantillas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column(
            "tipo_plantilla",
            sa.Enum("ALBUM", "CALENDARIO", name="tipoproyecto"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plantillas_id"), "plantillas", ["id"], unique=False)
    op.create_table(
        "suscripciones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("precio", sa.Float(), nullable=False),
        sa.Column("limite_almacenamiento_mb", sa.Integer(), nullable=False),
        sa.Column("nivel_plan", sa.Integer(), nullable=False),
        sa.Column("esta_activo", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_index(op.f("ix_suscripciones_id"), "suscripciones", ["id"], unique=False)
    op.create_table(
        "paginas_plantilla",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("numero_pagina", sa.Integer(), nullable=False),
        sa.Column("diseno_html", sa.Text(), nullable=True),
        sa.Column("plantilla_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plantilla_id"],
            ["plantillas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_paginas_plantilla_id"), "paginas_plantilla", ["id"], unique=False
    )
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("contrasena_hash", sa.String(length=255), nullable=False),
        sa.Column("nombre_completo", sa.String(length=255), nullable=True),
        sa.Column("url_imagen_perfil", sa.String(length=512), nullable=True),
        sa.Column("idioma", sa.String(length=10), nullable=True),
        sa.Column("esta_activo", sa.Boolean(), nullable=True),
        sa.Column("esta_verificado", sa.Boolean(), nullable=True),
        sa.Column("ultimo_acceso", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("fecha_modificacion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suscripcion_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["suscripcion_id"],
            ["suscripciones.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usuarios_email"), "usuarios", ["email"], unique=True)
    op.create_index(op.f("ix_usuarios_id"), "usuarios", ["id"], unique=False)
    op.create_table(
        "fotos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(length=255), nullable=True),
        sa.Column("url_almacenamiento", sa.String(length=512), nullable=False),
        sa.Column("tamano_archivo_kb", sa.Float(), nullable=True),
        sa.Column("ubicacion", sa.String(length=255), nullable=True),
        sa.Column("fecha_captura", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "estado", sa.Enum("ACTIVA", "ELIMINADA", name="estadofoto"), nullable=False
        ),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_modificacion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usuario_creacion_id", sa.Integer(), nullable=False),
        sa.Column("usuario_modificacion_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["usuario_creacion_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_modificacion_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fotos_id"), "fotos", ["id"], unique=False)
    op.create_table(
        "proyectos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column(
            "tipo_proyecto",
            sa.Enum("ALBUM", "CALENDARIO", name="tipoproyecto"),
            nullable=False,
        ),
        sa.Column("url_imagen_portada", sa.String(length=512), nullable=True),
        sa.Column(
            "visibilidad",
            sa.Enum("PUBLICO", "PRIVADO", name="visibilidadproyecto"),
            nullable=False,
        ),
        sa.Column(
            "estado",
            sa.Enum("ACTIVO", "ARCHIVADO", name="estadoproyecto"),
            nullable=False,
        ),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_modificacion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usuario_creacion_id", sa.Integer(), nullable=False),
        sa.Column("usuario_modificacion_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["usuario_creacion_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_modificacion_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_proyectos_id"), "proyectos", ["id"], unique=False)
    op.create_table(
        "paginas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("numero_pagina", sa.Integer(), nullable=False),
        sa.Column("proyecto_id", sa.Integer(), nullable=False),
        sa.Column("plantilla_origen_id", sa.Integer(), nullable=True),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_modificacion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usuario_creacion_id", sa.Integer(), nullable=False),
        sa.Column("usuario_modificacion_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["plantilla_origen_id"],
            ["paginas_plantilla.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyectos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_creacion_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_modificacion_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_paginas_id"), "paginas", ["id"], unique=False)
    op.create_table(
        "proyecto_categoria",
        sa.Column("proyecto_id", sa.Integer(), nullable=False),
        sa.Column("categoria_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["categoria_id"],
            ["categorias.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyectos.id"],
        ),
        sa.PrimaryKeyConstraint("proyecto_id", "categoria_id"),
    )
    op.create_table(
        "proyecto_colaboradores",
        sa.Column("proyecto_id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column(
            "rol",
            sa.Enum("PROPIETARIO", "EDITOR", "VISUALIZADOR", name="rolcolaborador"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyectos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("proyecto_id", "usuario_id"),
    )
    op.create_table(
        "elementos_pagina",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pagina_id", sa.Integer(), nullable=False),
        sa.Column(
            "tipo_elemento",
            sa.Enum("IMAGEN", "TEXTO", "FORMA", name="tipoelemento"),
            nullable=False,
        ),
        sa.Column("posicion_x", sa.Float(), nullable=True),
        sa.Column("posicion_y", sa.Float(), nullable=True),
        sa.Column("ancho", sa.Float(), nullable=True),
        sa.Column("alto", sa.Float(), nullable=True),
        sa.Column("rotacion", sa.Float(), nullable=True),
        sa.Column("orden_capa", sa.Integer(), nullable=True),
        sa.Column("contenido", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_modificacion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usuario_creacion_id", sa.Integer(), nullable=False),
        sa.Column("usuario_modificacion_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pagina_id"],
            ["paginas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_creacion_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_modificacion_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_elementos_pagina_id"), "elementos_pagina", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_elementos_pagina_id"), table_name="elementos_pagina")
    op.drop_table("elementos_pagina")
    op.drop_table("proyecto_colaboradores")
    op.drop_table("proyecto_categoria")
    op.drop_index(op.f("ix_paginas_id"), table_name="paginas")
    op.drop_table("paginas")
    op.drop_index(op.f("ix_proyectos_id"), table_name="proyectos")
    op.drop_table("proyectos")
    op.drop_index(op.f("ix_fotos_id"), table_name="fotos")
    op.drop_table("fotos")
    op.drop_index(op.f("ix_usuarios_id"), table_name="usuarios")
    op.drop_index(op.f("ix_usuarios_email"), table_name="usuarios")
    op.drop_table("usuarios")
    op.drop_index(op.f("ix_paginas_plantilla_id"), table_name="paginas_plantilla")
    op.drop_table("paginas_plantilla")
    op.drop_index(op.f("ix_suscripciones_id"), table_name="suscripciones")
    op.drop_table("suscripciones")
    op.drop_index(op.f("ix_plantillas_id"), table_name="plantillas")
    op.drop_table("plantillas")
    op.drop_index(op.f("ix_categorias_id"), table_name="categorias")
    op.drop_table("categorias")
    # ### end Alembic commands ###
